# Generated by Django 2.1 on 2020-04-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WYR_Queries', '0006_auto_20200329_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='WYR_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('queries_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WYR_Queries.Queries')),
            ],
        ),
    ]
