# Generated by Django 2.1 on 2020-04-04 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WYR_Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyr_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='wyr_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='wyr_user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='wyr_user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='wyr_user',
            name='username',
        ),
        migrations.AddField(
            model_name='wyr_user',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
