# Generated by Django 2.1 on 2020-04-19 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WYR_Users', '0002_auto_20200404_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyr_user',
            name='profile',
        ),
        migrations.AddField(
            model_name='wyr_user',
            name='Profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wyr_user',
            name='queries_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WYR_Queries.Queries'),
        ),
    ]
