# Generated by Django 2.1 on 2020-04-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WYR_Users', '0003_auto_20200418_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyr_user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
