# Generated by Django 2.1 on 2020-03-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=255)),
                ('Q1', models.CharField(max_length=300)),
                ('Q2', models.CharField(max_length=300)),
            ],
        ),
    ]
