# Generated by Django 2.1 on 2020-03-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WYR_Queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='Qimg1',
            field=models.ImageField(blank=True, upload_to='Q_img'),
        ),
        migrations.AddField(
            model_name='queries',
            name='Qimg2',
            field=models.ImageField(blank=True, upload_to='Q_img'),
        ),
    ]
