# Generated by Django 2.1 on 2020-03-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WYR_Queries', '0003_auto_20200327_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WYR_Queries.Categories'),
        ),
    ]
