# Generated by Django 2.1 on 2020-03-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WYR_Queries', '0005_auto_20200327_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='categories',
        ),
        migrations.AddField(
            model_name='queries',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
