# Generated by Django 2.1 on 2020-08-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WYR_Queries', '0006_auto_20200329_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='category',
        ),
    ]
